language: java

# since not all JDKs are available in all environments
matrix:
  include:
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: linux
      dist: trusty
      jdk: openjdk10
    - os: linux
      dist: trusty
      jdk: openjdk11
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: linux
      dist: trusty
      jdk: oraclejdk11
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1
#    - os: windows
#      jdk: jdk8
#    - os: windows
#      jdk: jdk10
# As Windows isn't quite ready yet

git:
  depth: 10

before_script:
  - echo $HOME
  - java -version
  - echo $JAVA_OPTS
  - mvn -version
  - echo $MAVEN_OPTS

cache:
  directories:
    - $HOME/.m2/

script:
  - mvn clean
  - mvn package -DskipTests
  - mvn test